baseURL = "https://countdigi.github.io/"

languageCode = "en-us"

title = "Kevin Counts"

disableKinds = ["taxonomyTerm"]

pygmentsCodeFences = true

pygmentsStyle = "friendly"

pygmentsOptions = "linenos=table"

[permalinks]
  posts = "/:year/:month/:slug/"

[params]
authors = ["Kevin M. Counts"]
og_image = "images/countdigi-avatar.png"

[params.sns]
github = "countdigi"
twitter = "countdigi"
