baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hugo Blog"

disableKinds = ["taxonomyTerm"]

pygmentsCodeFences = true

pygmentsStyle = "colorful"

pygmentsOptions = "linenos=table"

[permalinks]
  post = "/post/:slug/"

[params]
  homeText = "You just made a Hugo blog from scratch."




