baseURL = "https://digicat.org/"

languageCode = "en-us"

title = "Digicat.org - Personal Blog of Kevin Counts"

disableKinds = ["taxonomyTerm"]

pygmentsCodeFences = true

pygmentsStyle = "colorful"

pygmentsOptions = "linenos=table"

[permalinks]
  posts = "/:year/:month/:slug/"

[params]
authors = ["Kevin M. Counts"]

[params.sns]
github = "countdigi"
twitter = "countdigi"
